name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: check system version
        run: "uname -a; ln -s /usr/include/asm-generic /usr/include/asm;ls -al /usr/include; "

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - name: "Install LLVM"
        run: "sudo apt-get install -y llvm ; llvm-strip --version; sudo apt-get install -y --reinstall libc6-dev"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: make build

