name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: check system version
        run: "uname -a; ls -al /usr/include; "

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "16.0"

      - name: llvm-check
        run: ls -al "/home/runner/work/my_durdur/my_durdur/llvm"; ls -al /home/runner/work/my_durdur/my_durdur/llvm/bin;

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: export PATH="$PATH:/home/runner/work/my_durdur/my_durdur/llvm/bin";make build

